repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6  # use latest
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 24.4.2  # use latest
    hooks:
      - id: black