import yfinance as yf
import datetime as dt
import os


def download_ohlcv(ticker_list, path="./code/data_yf", start_date=None, end_date=None):
    """
    Download daily OHLCV data for a list of tickers from yfinance.

    Parameters:
        ticker_list (list): List of ticker symbols (strings)
        start_date (str): Optional, e.g. '2020-01-01'
        end_date (str): Optional, e.g. '2023-08-01'

    Returns:
        dict of pd.DataFrame: Each key is a ticker, value is its OHLCV DataFrame
    """
    for ticker in ticker_list:
        print(f"Downloading {ticker}...")
        df = yf.download(
            ticker, start=start_date, end=end_date, progress=False, auto_adjust=True
        )
        if df.empty:
            print(f"Warning: No data for {ticker}")
        else:
            # Keep only required columns
            df = df[["Open", "High", "Low", "Close", "Volume"]]
            start_dt = dt.datetime.strptime(start_date, "%Y-%m-%d")
            end_dt = dt.datetime.strptime(end_date, "%Y-%m-%d")
            filename = (
                ticker
                + "_"
                + dt.datetime.strftime(start_dt, format="%y%m%d")
                + "_"
                + dt.datetime.strftime(end_dt, format="%y%m%d")
                + ".csv"
            )
            df.to_csv(os.path.join(path, filename))
    return None


if __name__ == "__main__":
    # Example usage
    ticker_list = [
        "AAPL",
        "ABC",
        "ABMD",
        "ABT",
        "ADBE",
        "ADI",
        "ADM",
        "ADP",
        "ADSK",
        "AEP",
        "AES",
        "AFL",
        "AIG",
        "AJG",
        "ALB",
        "ALK",
        "ALL",
        "AMAT",
        "AMD",
        "AME",
        "AMGN",
        "AON",
        "AOS",
        "APA",
        "APD",
        "APH",
        "ATO",
        "ATVI",
        "AVB",
        "AVY",
        "AXP",
        "AZO",
        "BAC",
        "BALL",
        "BAX",
        "BA",
        "BBWI",
        "BBY",
        "BDX",
        "BEN",
        "BIIB",
        "BIO",
        "BKR",
        "BK",
        "BMY",
        "BRO",
        "BSX",
        "BWA",
        "CAG",
        "CAH",
        "CAT",
        "CB",
        "CCL",
        "CDNS",
        "CHD",
        "CINF",
        "CI",
        "CLX",
        "CL",
        "CMA",
        "CMCSA",
        "CMI",
        "CMS",
        "CNP",
        "COF",
        "COO",
        "COP",
        "COST",
        "CPB",
        "CPRT",
        "CPT",
        "CSCO",
        "CSX",
        "CTAS",
        "CTRA",
        "CTXS",
        "CVS",
        "CVX",
        "C",
        "DD",
        "DE",
        "DHI",
        "DHR",
        "DISH",
        "DIS",
        "DLTR",
        "DOV",
        "DRE",
        "DRI",
        "DTE",
        "DUK",
        "DVA",
        "DVN",
        "DXC",
        "D",
        "EA",
        "ECL",
        "ED",
        "EFX",
        "EIX",
        "EL",
        "EMN",
        "EMR",
        "EOG",
        "EQR",
        "ESS",
        "ES",
        "ETN",
        "ETR",
        "EVRG",
        "EXC",
        "EXPD",
        "FAST",
        "FCX",
        "FDX",
        "FISV",
        "FITB",
        "FMC",
        "FRT",
        "F",
        "GD",
        "GE",
        "GILD",
        "GIS",
        "GLW",
        "GL",
        "GPC",
        "GWW",
        "HAL",
        "HAS",
        "HBAN",
        "HD",
        "HES",
        "HIG",
        "HOLX",
        "HON",
        "HPQ",
        "HRL",
        "HSIC",
        "HST",
        "HSY",
        "HUM",
        "IBM",
        "IDXX",
        "IEX",
        "IFF",
        "INCY",
        "INTC",
        "INTU",
        "IPG",
        "IP",
        "ITW",
        "IT",
        "IVZ",
        "JBHT",
        "JCI",
        "JKHY",
        "JNJ",
        "JPM",
        "J",
        "KEY",
        "KIM",
        "KLAC",
        "KMB",
        "KO",
        "KR",
        "K",
        "LEN",
        "LHX",
        "LH",
        "LIN",
        "LLY",
        "LMT",
        "LNC",
        "LNT",
        "LOW",
        "LRCX",
        "LUMN",
        "LUV",
        "L",
        "MAA",
        "MAS",
        "MCD",
        "MCHP",
        "MCK",
        "MCO",
        "MDT",
        "MGM",
        "MHK",
        "MKC",
        "MLM",
        "MMC",
        "MMM",
        "MNST",
        "MOS",
        "MO",
        "MRK",
        "MRO",
        "MSFT",
        "MSI",
        "MS",
        "MTB",
        "MTCH",
        "MU",
        "NDSN",
        "NEE",
        "NEM",
        "NI",
        "NKE",
        "NLOK",
        "NOC",
        "NSC",
        "NTAP",
        "NTRS",
        "NUE",
        "NVR",
        "NWL",
        "ODFL",
        "OKE",
        "OMC",
        "ORCL",
        "ORLY",
        "OXY",
        "O",
        "PAYX",
        "PCAR",
        "PEAK",
        "PEG",
        "PENN",
        "PEP",
        "PFE",
        "PGR",
        "PG",
        "PHM",
        "PH",
        "PKI",
        "PNC",
        "PNR",
        "PNW",
        "POOL",
        "PPG",
        "PPL",
        "PSA",
        "PTC",
        "PVH",
        "QCOM",
        "RCL",
        "REGN",
        "REG",
        "RE",
        "RF",
        "RHI",
        "RJF",
        "RMD",
        "ROK",
        "ROL",
        "ROP",
        "ROST",
        "RTX",
        "SBUX",
        "SCHW",
        "SEE",
        "SHW",
        "SIVB",
        "SJM",
        "SLB",
        "SNA",
        "SNPS",
        "SO",
        "SPGI",
        "SPG",
        "STE",
        "STT",
        "STZ",
        "SWKS",
        "SWK",
        "SYK",
        "SYY",
        "TAP",
        "TECH",
        "TER",
        "TFC",
        "TFX",
        "TGT",
        "TJX",
        "TMO",
        "TRMB",
        "TROW",
        "TRV",
        "TSCO",
        "TSN",
        "TT",
        "TXN",
        "TXT",
        "TYL",
        "T",
        "UDR",
        "UHS",
        "UNH",
        "UNP",
        "USB",
        "VFC",
        "VLO",
        "VMC",
        "VNO",
        "VRTX",
        "VTRS",
        "VZ",
        "WAB",
        "WAT",
        "WBA",
        "WDC",
        "WEC",
        "WELL",
        "WFC",
        "WHR",
        "WMB",
        "WMT",
        "WM",
        "WRB",
        "WST",
        "WY",
        "XEL",
        "XOM",
        "XRAY",
        "ZBRA",
        "ZION",
    ]
    # ticker_list = ['AAPL', 'MSFT', 'GOOGL']
    for year in range(2010, 2025):
        path = os.path.join(".", "code", "data_yf", str(year))
        os.mkdir(path)
        ohlcv_data = download_ohlcv(
            ticker_list,
            path=path,
            start_date=str(year) + "-01-01",
            end_date=str(year + 1) + "-01-01",
        )
